version '3'

services:
  nginx:
    container_name: nginx
    build: ./required/nginx
    depends_on:
      - adminer
      - redis
      - hugo
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

